INSERT INTO directions (order_number, description, dish_fk_id) VALUES 
(1, 'It uses a dictionary of over 200 Latin words, combined with a handful of model generate Lorem Ipsum which looks reasonable. ', 1),
(2, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 1),
(3, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour.', 1),
(4, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 1),
(5, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour.', 1),
(1, 'There are many variations of passages of but the majority have suffered alteration in some form, by injected humour, or randomised words which', 2),
(2, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 2),
(3, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour.', 2),
(1, 'There are many variations of passages of but the majority have suffered alteration in some form, by injected humour, or randomised words which', 3),
(2, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 3),
(3, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour.', 3),
(1, 'There are many variations of passages of but the majority have suffered alteration in some form, by injected humour, or randomised words which', 4),
(2, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 4),
(3, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour.', 4),
(1, 'There are many variations of passages of but the majority have suffered alteration in some form, by injected humour, or randomised words which', 5),
(2, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 5),
(3, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour.', 5),
(1, 'There are many variations of passages of but the majority have suffered alteration in some form, by injected humour, or randomised words which', 6),
(2, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.', 6),
(3, 'The generated Lorem Ipsum is therefore always free from repetition, injected humour.', 6);
