INSERT INTO ingredient (name, description, quantity, measurment_unit, measurment_descriptor, dish_fk_id) VALUES 
('Meat', 'The generated Lorem Ipsum is therefore always free from repetition', 4, 'Whole', 'Trimmed', 1),
('Butter', 'The generated Lorem Ipsum is  non-characteristic words etc.', 4, 'Tbs', 'Softened', 1),
('Seasoning', 'The generated Lorem Ipsum is therefore always free from repetition, injected humour.', 2, 'Tbs', 'Packed', 1),
('Beef', 'The generated Lorem  or non-characteristic words etc.', 4, 'Pounds', 'Ground', 2),
('Egg', 'The generated Lorem  or non-characteristic words etc.', 3, 'Whole', 'Beaten', 2),
('Seasoning', 'The repetition, injected humour.', 3, 'Tbs', 'Packed', 2),
('Ribs', 'The generated Lorem Ipsum is therefore al or non-characteristic words etc.', 4, 'Racks', 'Trimmed', 3),
('Sauce', 'The generated Lorem Ipsum is therefore or non-characteristic words etc.', 1, 'Cup', 'N/A', 3),
('Butter', 'The generated Lorem Ipsum is therefore always.', 3, 'Tbs', 'Softened', 3),
('Banana', 'The generated Lorem Ipsum is humour, or non-characteristic words etc.', 4, 'Whole', 'Peeled', 4),
('Brown Sugar', 'The generated Lorem humour, or non-characteristic words etc.', 2, 'Cups', 'Packed', 4),
('Butter', 'The generated Lorem Ipsum ', 1, 'Cup', 'Softened', 4),
('Cream', 'The generated Lorem Ipsum is therefore always free  words etc.', 1, 'Cup', 'Stirred', 5),
('Sugar', 'The generated e from repetition, injected humour, or non-characteristic', 2, 'Cups', 'Packed', 5),
('Butter', 'The generated Lorem Ipsum is ', 1, 'Cup', 'Softened', 5),
('Banana', 'The generated Lorem Ipsum is therefore always words etc.', 4, 'Whole', 'Peeled', 6),
('Cream', 'The generated Lorem Ipsum is therefore always free  words etc.', 2, 'Cups', 'Stirred', 6),
('Butter', 'The generated Lorem Ipsum is therefore always free from', 1, 'Cup', 'Softened', 6);
